name: Expo Publish
on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: mobile

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install --legacy-peer-deps

      - name: Publish to Expo
        run: npx expo publish --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_NO_TELEMETRY: 1